// <auto-generated/>
#nullable enable
namespace RacingGame.Client;

partial class ConnectForm
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
            components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        _lblTitle      = new Label();
        _lblSubtitle   = new Label();
        _lblName       = new Label();
        _txtName       = new TextBox();
        _lblServerIP   = new Label();
        _txtHost       = new TextBox();
        _lblPort       = new Label();
        _nudPort       = new NumericUpDown();
        _lblChooseCar  = new Label();
        _carPanel      = new Panel();
        _btnCar1       = new Button();
        _btnCar2       = new Button();
        _btnCar3       = new Button();
        _btnJoin       = new Button();
        _lblStatus     = new Label();
        _btnHelp       = new Button();
        _btnScores     = new Button();

        _nudPort.BeginInit();
        _carPanel.SuspendLayout();
        SuspendLayout();

        // _lblTitle
        _lblTitle.Name      = "lblTitle";
        _lblTitle.Text      = "🏎  NEON RACING 2026";
        _lblTitle.Font      = new Font("Segoe UI", 22, FontStyle.Bold);
        _lblTitle.ForeColor = Color.Cyan;
        _lblTitle.AutoSize  = true;
        _lblTitle.Location  = new Point(70, 30);

        // _lblSubtitle
        _lblSubtitle.Name      = "lblSubtitle";
        _lblSubtitle.Text      = "The Future of Racing Is Here";
        _lblSubtitle.Font      = new Font("Segoe UI", 10, FontStyle.Italic);
        _lblSubtitle.ForeColor = Color.FromArgb(100, 200, 230);
        _lblSubtitle.AutoSize  = true;
        _lblSubtitle.Location  = new Point(135, 78);

        // _lblName  ("Your Name:" label)
        _lblName.Name      = "lblName";
        _lblName.Text      = "Your Name:";
        _lblName.Location  = new Point(30, 112);
        _lblName.Size      = new Size(140, 28);
        _lblName.Font      = new Font("Segoe UI", 11);
        _lblName.ForeColor = Color.LightGray;
        _lblName.TextAlign = ContentAlignment.MiddleRight;

        // _txtName
        _txtName.Name        = "txtName";
        _txtName.Location    = new Point(170, 110);
        _txtName.Size        = new Size(220, 28);
        _txtName.Font        = new Font("Segoe UI", 11);
        _txtName.BackColor   = Color.FromArgb(18, 28, 40);
        _txtName.ForeColor   = Color.Cyan;
        _txtName.BorderStyle = BorderStyle.FixedSingle;

        // _lblServerIP  ("Server IP:" label)
        _lblServerIP.Name      = "lblServerIP";
        _lblServerIP.Text      = "Server IP:";
        _lblServerIP.Location  = new Point(30, 157);
        _lblServerIP.Size      = new Size(140, 28);
        _lblServerIP.Font      = new Font("Segoe UI", 11);
        _lblServerIP.ForeColor = Color.LightGray;
        _lblServerIP.TextAlign = ContentAlignment.MiddleRight;

        // _txtHost
        _txtHost.Name        = "txtHost";
        _txtHost.Location    = new Point(170, 155);
        _txtHost.Size        = new Size(160, 28);
        _txtHost.Text        = "127.0.0.1";
        _txtHost.Font        = new Font("Segoe UI", 11);
        _txtHost.BackColor   = Color.FromArgb(18, 28, 40);
        _txtHost.ForeColor   = Color.Cyan;
        _txtHost.BorderStyle = BorderStyle.FixedSingle;

        // _lblPort  ("Port:" label)
        _lblPort.Name      = "lblPort";
        _lblPort.Text      = "Port:";
        _lblPort.Location  = new Point(30, 202);
        _lblPort.Size      = new Size(140, 28);
        _lblPort.Font      = new Font("Segoe UI", 11);
        _lblPort.ForeColor = Color.LightGray;
        _lblPort.TextAlign = ContentAlignment.MiddleRight;

        // _nudPort
        _nudPort.Name      = "nudPort";
        _nudPort.Location  = new Point(170, 200);
        _nudPort.Size      = new Size(90, 28);
        _nudPort.Minimum   = 1;
        _nudPort.Maximum   = 65535;
        _nudPort.Value     = 9000;
        _nudPort.Font      = new Font("Segoe UI", 11);
        _nudPort.BackColor = Color.FromArgb(18, 28, 40);
        _nudPort.ForeColor = Color.Cyan;

        // _lblChooseCar  ("Choose Car:" label)
        _lblChooseCar.Name      = "lblChooseCar";
        _lblChooseCar.Text      = "Choose Car:";
        _lblChooseCar.Location  = new Point(30, 252);
        _lblChooseCar.Size      = new Size(140, 28);
        _lblChooseCar.Font      = new Font("Segoe UI", 11);
        _lblChooseCar.ForeColor = Color.LightGray;
        _lblChooseCar.TextAlign = ContentAlignment.MiddleRight;

        // _btnCar1
        _btnCar1.Name      = "btnCar1";
        _btnCar1.Text      = "🚗  Car 1";
        _btnCar1.Location  = new Point(0, 10);
        _btnCar1.Size      = new Size(115, 70);
        _btnCar1.Font      = new Font("Segoe UI", 10, FontStyle.Bold);
        _btnCar1.BackColor = Color.FromArgb(12, 20, 30);
        _btnCar1.ForeColor = Color.DeepSkyBlue;
        _btnCar1.FlatStyle = FlatStyle.Flat;
        _btnCar1.FlatAppearance.BorderColor = Color.DeepSkyBlue;
        _btnCar1.FlatAppearance.BorderSize  = 2;
        _btnCar1.Cursor    = Cursors.Hand;
        _btnCar1.Click    += (_, _) => SelectCar(1);

        // _btnCar2
        _btnCar2.Name      = "btnCar2";
        _btnCar2.Text      = "🏎  Car 2";
        _btnCar2.Location  = new Point(130, 10);
        _btnCar2.Size      = new Size(115, 70);
        _btnCar2.Font      = new Font("Segoe UI", 10, FontStyle.Bold);
        _btnCar2.BackColor = Color.FromArgb(12, 20, 30);
        _btnCar2.ForeColor = Color.OrangeRed;
        _btnCar2.FlatStyle = FlatStyle.Flat;
        _btnCar2.FlatAppearance.BorderColor = Color.OrangeRed;
        _btnCar2.FlatAppearance.BorderSize  = 2;
        _btnCar2.Cursor    = Cursors.Hand;
        _btnCar2.Click    += (_, _) => SelectCar(2);

        // _btnCar3
        _btnCar3.Name      = "btnCar3";
        _btnCar3.Text      = "🚙  Car 3";
        _btnCar3.Location  = new Point(260, 10);
        _btnCar3.Size      = new Size(115, 70);
        _btnCar3.Font      = new Font("Segoe UI", 10, FontStyle.Bold);
        _btnCar3.BackColor = Color.FromArgb(12, 20, 30);
        _btnCar3.ForeColor = Color.LimeGreen;
        _btnCar3.FlatStyle = FlatStyle.Flat;
        _btnCar3.FlatAppearance.BorderColor = Color.LimeGreen;
        _btnCar3.FlatAppearance.BorderSize  = 2;
        _btnCar3.Cursor    = Cursors.Hand;
        _btnCar3.Click    += (_, _) => SelectCar(3);

        // _carPanel  (holds the three car-selection buttons)
        _carPanel.Name      = "carPanel";
        _carPanel.Location  = new Point(60, 282);
        _carPanel.Size      = new Size(390, 100);
        _carPanel.BackColor = Color.Transparent;
        _carPanel.Controls.AddRange(new Control[] { _btnCar1, _btnCar2, _btnCar3 });

        // _btnJoin
        _btnJoin.Name      = "btnJoin";
        _btnJoin.Text      = "⚡  Join Game";
        _btnJoin.Location  = new Point(170, 397);
        _btnJoin.Size      = new Size(165, 44);
        _btnJoin.Font      = new Font("Segoe UI", 13, FontStyle.Bold);
        _btnJoin.BackColor = Color.FromArgb(0, 55, 75);
        _btnJoin.ForeColor = Color.Cyan;
        _btnJoin.FlatStyle = FlatStyle.Flat;
        _btnJoin.FlatAppearance.BorderColor = Color.Cyan;
        _btnJoin.FlatAppearance.BorderSize  = 2;
        _btnJoin.Cursor    = Cursors.Hand;
        _btnJoin.Click    += OnJoinClicked;

        // _lblStatus  (validation / connection status)
        _lblStatus.Name      = "lblStatus";
        _lblStatus.Location  = new Point(30, 451);
        _lblStatus.Size      = new Size(450, 30);
        _lblStatus.Font      = new Font("Segoe UI", 10);
        _lblStatus.ForeColor = Color.Tomato;
        _lblStatus.TextAlign = ContentAlignment.MiddleCenter;

        // _btnHelp  ("How to Play" button)
        _btnHelp.Name      = "btnHelp";
        _btnHelp.Text      = "How to Play";
        _btnHelp.Location  = new Point(80, 489);
        _btnHelp.Size      = new Size(140, 34);
        _btnHelp.Font      = new Font("Segoe UI", 10);
        _btnHelp.BackColor = Color.FromArgb(40, 60, 80);
        _btnHelp.ForeColor = Color.LightCyan;
        _btnHelp.FlatStyle = FlatStyle.Flat;
        _btnHelp.Cursor    = Cursors.Hand;
        _btnHelp.FlatAppearance.BorderSize  = 1;
        _btnHelp.FlatAppearance.BorderColor = Color.SteelBlue;
        _btnHelp.Click    += (_, _) => new HowToPlayForm().ShowDialog(this);

        // _btnScores  ("High Scores" button)
        _btnScores.Name      = "btnScores";
        _btnScores.Text      = "High Scores";
        _btnScores.Location  = new Point(290, 489);
        _btnScores.Size      = new Size(140, 34);
        _btnScores.Font      = new Font("Segoe UI", 10);
        _btnScores.BackColor = Color.FromArgb(60, 50, 20);
        _btnScores.ForeColor = Color.Gold;
        _btnScores.FlatStyle = FlatStyle.Flat;
        _btnScores.Cursor    = Cursors.Hand;
        _btnScores.FlatAppearance.BorderSize  = 1;
        _btnScores.FlatAppearance.BorderColor = Color.Goldenrod;
        _btnScores.Click    += (_, _) => ShowHighScores();

        // Form properties
        Name            = "ConnectForm";
        Text            = "Neon Racing 2026 – Connect";
        Size            = new Size(520, 580);
        StartPosition   = FormStartPosition.CenterScreen;
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox     = false;
        BackColor       = Color.FromArgb(8, 8, 18);
        ForeColor       = Color.White;
        Paint          += OnFormPaint;

        Controls.AddRange(new Control[]
        {
            _lblTitle,
            _lblSubtitle,
            _lblName,
            _txtName,
            _lblServerIP,
            _txtHost,
            _lblPort,
            _nudPort,
            _lblChooseCar,
            _carPanel,
            _btnJoin,
            _lblStatus,
            _btnHelp,
            _btnScores
        });

        _nudPort.EndInit();
        _carPanel.ResumeLayout(false);
        ResumeLayout(false);
        PerformLayout();
    }

    // ── Control field declarations ────────────────────────────────────────────
    private Label        _lblTitle     = null!;
    private Label        _lblSubtitle  = null!;
    private Label        _lblName      = null!;
    private TextBox      _txtName      = null!;
    private Label        _lblServerIP  = null!;
    private TextBox      _txtHost      = null!;
    private Label        _lblPort      = null!;
    private NumericUpDown _nudPort     = null!;
    private Label        _lblChooseCar = null!;
    private Panel        _carPanel     = null!;
    private Button       _btnCar1      = null!;
    private Button       _btnCar2      = null!;
    private Button       _btnCar3      = null!;
    private Button       _btnJoin      = null!;
    private Label        _lblStatus    = null!;
    private Button       _btnHelp      = null!;
    private Button       _btnScores    = null!;
}
