// <auto-generated/>
#nullable enable
namespace RacingGame.Client;

partial class GameForm
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
            components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        _lblStatus      = new Label();
        _lblPing        = new Label();
        _trackPanel     = new DoubleBufferedPanel();
        _lblWaiting     = new Label();
        _lblRaceTime    = new Label();
        _btnResign      = new Button();
        _btnReady       = new Button();
        _btnMove        = new Button();
        _btnRestart     = new Button();
        _btnQuit        = new Button();
        _reconnectPanel = new Panel();
        _lblReconnect   = new Label();
        _btnReturnToLobby = new Button();

        _trackPanel.SuspendLayout();
        _reconnectPanel.SuspendLayout();
        SuspendLayout();

        // _lblStatus  (top status bar)
        _lblStatus.Name      = "lblStatus";
        _lblStatus.Location  = new Point(10, 14);
        _lblStatus.Size      = new Size(780, 28);
        _lblStatus.Font      = new Font("Segoe UI", 11, FontStyle.Bold);
        _lblStatus.ForeColor = Color.Gold;
        _lblStatus.TextAlign = ContentAlignment.MiddleCenter;
        _lblStatus.Text      = "Waiting for players …";

        // _lblPing  (top-right latency display)
        _lblPing.Name      = "lblPing";
        _lblPing.Location  = new Point(795, 14);
        _lblPing.Size      = new Size(110, 28);
        _lblPing.Font      = new Font("Consolas", 10);
        _lblPing.ForeColor = Color.LimeGreen;
        _lblPing.TextAlign = ContentAlignment.MiddleRight;
        _lblPing.Text      = "Ping: –";

        // _lblWaiting  (overlay shown on the track before the race begins)
        _lblWaiting.Name      = "lblWaiting";
        _lblWaiting.Location  = new Point(200, 150);
        _lblWaiting.Size      = new Size(480, 100);
        _lblWaiting.Font      = new Font("Segoe UI", 16, FontStyle.Bold);
        _lblWaiting.ForeColor = Color.Cyan;
        _lblWaiting.BackColor = Color.Transparent;
        _lblWaiting.TextAlign = ContentAlignment.MiddleCenter;
        _lblWaiting.Text      = "Waiting for players …\nAt least 2 needed.  Click Ready!";

        // _trackPanel  (owner-drawn race track)
        _trackPanel.Name      = "trackPanel";
        _trackPanel.Location  = new Point(10, 50);
        _trackPanel.Size      = new Size(880, 420);
        _trackPanel.BackColor = Color.FromArgb(8, 8, 18);
        _trackPanel.Paint    += DrawTrack;
        _trackPanel.Controls.Add(_lblWaiting);

        // _lblRaceTime  (elapsed race time, bottom-left)
        _lblRaceTime.Name      = "lblRaceTime";
        _lblRaceTime.Location  = new Point(10, 496);
        _lblRaceTime.Size      = new Size(160, 28);
        _lblRaceTime.Font      = new Font("Consolas", 11);
        _lblRaceTime.ForeColor = Color.LightGray;
        _lblRaceTime.Text      = string.Empty;

        // _btnResign  (shown during race)
        _btnResign.Name      = "btnResign";
        _btnResign.Text      = "Resign";
        _btnResign.Location  = new Point(180, 490);
        _btnResign.Size      = new Size(120, 44);
        _btnResign.Font      = new Font("Segoe UI", 11, FontStyle.Bold);
        _btnResign.BackColor = Color.DarkRed;
        _btnResign.ForeColor = Color.White;
        _btnResign.FlatStyle = FlatStyle.Flat;
        _btnResign.FlatAppearance.BorderSize = 0;
        _btnResign.Cursor    = Cursors.Hand;
        _btnResign.Visible   = false;
        _btnResign.Click    += OnResignClicked;

        // _btnReady  (shown in the waiting room)
        _btnReady.Name      = "btnReady";
        _btnReady.Text      = "I'm Ready!";
        _btnReady.Location  = new Point(310, 490);
        _btnReady.Size      = new Size(160, 44);
        _btnReady.Font      = new Font("Segoe UI", 13, FontStyle.Bold);
        _btnReady.BackColor = Color.ForestGreen;
        _btnReady.ForeColor = Color.White;
        _btnReady.FlatStyle = FlatStyle.Flat;
        _btnReady.FlatAppearance.BorderSize = 0;
        _btnReady.Cursor    = Cursors.Hand;
        _btnReady.Click    += OnReadyClicked;

        // _btnMove  (shown during the race)
        _btnMove.Name      = "btnMove";
        _btnMove.Text      = "MOVE!";
        _btnMove.Location  = new Point(490, 490);
        _btnMove.Size      = new Size(200, 44);
        _btnMove.Font      = new Font("Segoe UI", 14, FontStyle.Bold);
        _btnMove.BackColor = Color.DodgerBlue;
        _btnMove.ForeColor = Color.White;
        _btnMove.FlatStyle = FlatStyle.Flat;
        _btnMove.FlatAppearance.BorderSize = 0;
        _btnMove.Cursor    = Cursors.Hand;
        _btnMove.Enabled   = false;
        _btnMove.Visible   = false;
        _btnMove.Click    += OnMoveClicked;

        // _btnRestart  ("Play Again" shown after the race)
        _btnRestart.Name      = "btnRestart";
        _btnRestart.Text      = "Play Again";
        _btnRestart.Location  = new Point(310, 490);
        _btnRestart.Size      = new Size(160, 44);
        _btnRestart.Font      = new Font("Segoe UI", 13, FontStyle.Bold);
        _btnRestart.BackColor = Color.DodgerBlue;
        _btnRestart.ForeColor = Color.White;
        _btnRestart.FlatStyle = FlatStyle.Flat;
        _btnRestart.FlatAppearance.BorderSize = 0;
        _btnRestart.Cursor    = Cursors.Hand;
        _btnRestart.Visible   = false;
        _btnRestart.Click    += (_, _) => Close();

        // _btnQuit  ("Quit" shown after the race)
        _btnQuit.Name      = "btnQuit";
        _btnQuit.Text      = "Quit";
        _btnQuit.Location  = new Point(490, 490);
        _btnQuit.Size      = new Size(200, 44);
        _btnQuit.Font      = new Font("Segoe UI", 13, FontStyle.Bold);
        _btnQuit.BackColor = Color.Firebrick;
        _btnQuit.ForeColor = Color.White;
        _btnQuit.FlatStyle = FlatStyle.Flat;
        _btnQuit.FlatAppearance.BorderSize = 0;
        _btnQuit.Cursor    = Cursors.Hand;
        _btnQuit.Visible   = false;
        _btnQuit.Click    += (_, _) => Close();

        // _lblReconnect  (inside reconnect panel)
        _lblReconnect.Name      = "lblReconnect";
        _lblReconnect.Location  = new Point(10, 10);
        _lblReconnect.Size      = new Size(460, 36);
        _lblReconnect.Font      = new Font("Segoe UI", 11, FontStyle.Bold);
        _lblReconnect.ForeColor = Color.OrangeRed;
        _lblReconnect.TextAlign = ContentAlignment.MiddleLeft;
        _lblReconnect.Text      = "Connection lost!";

        // _btnReturnToLobby  (inside reconnect panel)
        _btnReturnToLobby.Name      = "btnReturnToLobby";
        _btnReturnToLobby.Text      = "Return to Lobby";
        _btnReturnToLobby.Location  = new Point(490, 8);
        _btnReturnToLobby.Size      = new Size(170, 38);
        _btnReturnToLobby.Font      = new Font("Segoe UI", 10, FontStyle.Bold);
        _btnReturnToLobby.BackColor = Color.DodgerBlue;
        _btnReturnToLobby.ForeColor = Color.White;
        _btnReturnToLobby.FlatStyle = FlatStyle.Flat;
        _btnReturnToLobby.Cursor    = Cursors.Hand;
        _btnReturnToLobby.FlatAppearance.BorderSize = 0;
        _btnReturnToLobby.Click    += (_, _) => Close();

        // _reconnectPanel  (overlay shown when the TCP connection is lost)
        _reconnectPanel.Name      = "reconnectPanel";
        _reconnectPanel.Location  = new Point(10, 485);
        _reconnectPanel.Size      = new Size(880, 60);
        _reconnectPanel.BackColor = Color.FromArgb(50, 0, 0);
        _reconnectPanel.Visible   = false;
        _reconnectPanel.Controls.AddRange(new Control[] { _lblReconnect, _btnReturnToLobby });

        // Form properties
        Name            = "GameForm";
        Text            = "Racing Game";
        Size            = new Size(920, 590);
        StartPosition   = FormStartPosition.CenterScreen;
        FormBorderStyle = FormBorderStyle.FixedSingle;
        MaximizeBox     = false;
        BackColor       = Color.FromArgb(15, 15, 25);
        ForeColor       = Color.White;

        Controls.AddRange(new Control[]
        {
            _lblStatus,
            _lblPing,
            _trackPanel,
            _lblRaceTime,
            _btnResign,
            _btnReady,
            _btnMove,
            _btnRestart,
            _btnQuit,
            _reconnectPanel
        });

        _trackPanel.ResumeLayout(false);
        _reconnectPanel.ResumeLayout(false);
        ResumeLayout(false);
    }

    // ── Control field declarations ────────────────────────────────────────────
    private Label               _lblStatus        = null!;
    private Label               _lblPing          = null!;
    private DoubleBufferedPanel _trackPanel       = null!;
    private Label               _lblWaiting       = null!;
    private Label               _lblRaceTime      = null!;
    private Button              _btnResign        = null!;
    private Button              _btnReady         = null!;
    private Button              _btnMove          = null!;
    private Button              _btnRestart       = null!;
    private Button              _btnQuit          = null!;
    private Panel               _reconnectPanel   = null!;
    private Label               _lblReconnect     = null!;
    private Button              _btnReturnToLobby = null!;
}
