// <auto-generated/>
#nullable enable
namespace RacingGame.Client;

partial class HowToPlayForm
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
            components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        _lblTitle        = new Label();
        _rtbInstructions = new RichTextBox();
        _btnClose        = new Button();

        SuspendLayout();

        // _lblTitle
        _lblTitle.Name      = "lblTitle";
        _lblTitle.Text      = "How to Play";
        _lblTitle.Font      = new Font("Segoe UI", 18, FontStyle.Bold);
        _lblTitle.ForeColor = Color.Gold;
        _lblTitle.AutoSize  = true;
        _lblTitle.Location  = new Point(20, 15);

        // _rtbInstructions
        _rtbInstructions.Name        = "rtbInstructions";
        _rtbInstructions.Location    = new Point(15, 55);
        _rtbInstructions.Size        = new Size(475, 390);
        _rtbInstructions.BackColor   = Color.FromArgb(30, 30, 45);
        _rtbInstructions.ForeColor   = Color.White;
        _rtbInstructions.Font        = new Font("Segoe UI", 11);
        _rtbInstructions.ReadOnly    = true;
        _rtbInstructions.BorderStyle = BorderStyle.None;
        _rtbInstructions.ScrollBars  = RichTextBoxScrollBars.Vertical;
        _rtbInstructions.Text        = GetInstructions();

        // _btnClose  ("Got it!" button)
        _btnClose.Name         = "btnClose";
        _btnClose.Text         = "Got it!";
        _btnClose.Location     = new Point(190, 460);
        _btnClose.Size         = new Size(130, 40);
        _btnClose.Font         = new Font("Segoe UI", 12, FontStyle.Bold);
        _btnClose.BackColor    = Color.DodgerBlue;
        _btnClose.ForeColor    = Color.White;
        _btnClose.FlatStyle    = FlatStyle.Flat;
        _btnClose.Cursor       = Cursors.Hand;
        _btnClose.DialogResult = DialogResult.OK;
        _btnClose.FlatAppearance.BorderSize = 0;

        // Form properties
        Name            = "HowToPlayForm";
        Text            = "How to Play – Racing Game";
        Size            = new Size(520, 540);
        StartPosition   = FormStartPosition.CenterParent;
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox     = false;
        MinimizeBox     = false;
        BackColor       = Color.FromArgb(20, 20, 30);
        ForeColor       = Color.White;
        AcceptButton    = _btnClose;

        Controls.AddRange(new Control[]
        {
            _lblTitle,
            _rtbInstructions,
            _btnClose
        });

        ResumeLayout(false);
        PerformLayout();
    }

    // ── Control field declarations ────────────────────────────────────────────
    private Label       _lblTitle        = null!;
    private RichTextBox _rtbInstructions = null!;
    private Button      _btnClose        = null!;
}
