// <auto-generated/>
#nullable enable
using System.Drawing.Drawing2D;

namespace RacingGame.Server;

partial class ServerForm
{
    private System.ComponentModel.IContainer? components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
            components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        _lblTitle          = new Label();
        _lblSubtitle       = new Label();
        _lblBindIP         = new Label();
        _cboIp             = new ComboBox();
        _lblPort           = new Label();
        _nudPort           = new NumericUpDown();
        _lblMaxPlayers     = new Label();
        _btnStart          = new Button();
        _lblConnectedPlayers = new Label();
        _lstPlayers        = new ListBox();
        _lblServerLog      = new Label();
        _rtbLog            = new RichTextBox();

        _nudPort.BeginInit();
        SuspendLayout();

        // _lblTitle
        _lblTitle.Name      = "lblTitle";
        _lblTitle.Text      = "🏎  Neon Racing 2026 – Server";
        _lblTitle.Font      = new Font("Segoe UI", 16, FontStyle.Bold);
        _lblTitle.ForeColor = Color.Cyan;
        _lblTitle.AutoSize  = true;
        _lblTitle.Location  = new Point(20, 20);

        // _lblSubtitle
        _lblSubtitle.Name      = "lblSubtitle";
        _lblSubtitle.Text      = "AI bots fill empty slots automatically when a player clicks \"I'm Ready!\"";
        _lblSubtitle.Font      = new Font("Segoe UI", 9, FontStyle.Italic);
        _lblSubtitle.ForeColor = Color.FromArgb(100, 200, 230);
        _lblSubtitle.AutoSize  = true;
        _lblSubtitle.Location  = new Point(20, 65);

        // _lblBindIP  ("Bind IP:" label)
        _lblBindIP.Name      = "lblBindIP";
        _lblBindIP.Text      = "Bind IP:";
        _lblBindIP.Location  = new Point(20, 100);
        _lblBindIP.Size      = new Size(125, 28);
        _lblBindIP.Font      = new Font("Segoe UI", 11);
        _lblBindIP.ForeColor = Color.LightGray;
        _lblBindIP.TextAlign = ContentAlignment.MiddleRight;

        // _cboIp  (IP address drop-down — items are populated at runtime)
        _cboIp.Name          = "cboIp";
        _cboIp.Location      = new Point(150, 98);
        _cboIp.Size          = new Size(200, 28);
        _cboIp.DropDownStyle = ComboBoxStyle.DropDownList;
        _cboIp.Font          = new Font("Segoe UI", 11);
        _cboIp.BackColor     = Color.FromArgb(18, 28, 40);
        _cboIp.ForeColor     = Color.Cyan;

        // _lblPort  ("Port:" label)
        _lblPort.Name      = "lblPort";
        _lblPort.Text      = "Port:";
        _lblPort.Location  = new Point(20, 145);
        _lblPort.Size      = new Size(125, 28);
        _lblPort.Font      = new Font("Segoe UI", 11);
        _lblPort.ForeColor = Color.LightGray;
        _lblPort.TextAlign = ContentAlignment.MiddleRight;

        // _nudPort
        _nudPort.Name      = "nudPort";
        _nudPort.Location  = new Point(150, 143);
        _nudPort.Size      = new Size(110, 28);
        _nudPort.Minimum   = 1;
        _nudPort.Maximum   = 65535;
        _nudPort.Value     = 9000;
        _nudPort.Font      = new Font("Segoe UI", 11);
        _nudPort.BackColor = Color.FromArgb(18, 28, 40);
        _nudPort.ForeColor = Color.Cyan;

        // _lblMaxPlayers  (info label)
        _lblMaxPlayers.Name      = "lblMaxPlayers";
        _lblMaxPlayers.Text      = "Max Players: 5  (human + bots combined)";
        _lblMaxPlayers.Font      = new Font("Segoe UI", 9);
        _lblMaxPlayers.ForeColor = Color.DarkGray;
        _lblMaxPlayers.AutoSize  = true;
        _lblMaxPlayers.Location  = new Point(150, 190);

        // _btnStart  (Start / Stop toggle)
        _btnStart.Name      = "btnStart";
        _btnStart.Text      = "▶  Start Server";
        _btnStart.Location  = new Point(150, 220);
        _btnStart.Size      = new Size(170, 44);
        _btnStart.Font      = new Font("Segoe UI", 13, FontStyle.Bold);
        _btnStart.BackColor = Color.FromArgb(0, 70, 20);
        _btnStart.ForeColor = Color.LimeGreen;
        _btnStart.FlatStyle = FlatStyle.Flat;
        _btnStart.FlatAppearance.BorderColor = Color.LimeGreen;
        _btnStart.FlatAppearance.BorderSize  = 2;
        _btnStart.Cursor    = Cursors.Hand;
        _btnStart.Click    += OnStartStopClicked;

        // _lblConnectedPlayers
        _lblConnectedPlayers.Name      = "lblConnectedPlayers";
        _lblConnectedPlayers.Text      = "Connected Players:";
        _lblConnectedPlayers.Location  = new Point(20, 282);
        _lblConnectedPlayers.Size      = new Size(200, 24);
        _lblConnectedPlayers.Font      = new Font("Segoe UI", 10, FontStyle.Bold);
        _lblConnectedPlayers.ForeColor = Color.Cyan;

        // _lstPlayers
        _lstPlayers.Name        = "lstPlayers";
        _lstPlayers.Location    = new Point(20, 308);
        _lstPlayers.Size        = new Size(195, 310);
        _lstPlayers.Font        = new Font("Segoe UI", 10);
        _lstPlayers.BackColor   = Color.FromArgb(10, 18, 28);
        _lstPlayers.ForeColor   = Color.Cyan;
        _lstPlayers.BorderStyle = BorderStyle.FixedSingle;

        // _lblServerLog
        _lblServerLog.Name      = "lblServerLog";
        _lblServerLog.Text      = "Server Log:";
        _lblServerLog.Location  = new Point(230, 282);
        _lblServerLog.Size      = new Size(150, 24);
        _lblServerLog.Font      = new Font("Segoe UI", 10, FontStyle.Bold);
        _lblServerLog.ForeColor = Color.Cyan;

        // _rtbLog
        _rtbLog.Name        = "rtbLog";
        _rtbLog.Location    = new Point(230, 308);
        _rtbLog.Size        = new Size(385, 310);
        _rtbLog.Font        = new Font("Consolas", 9);
        _rtbLog.BackColor   = Color.FromArgb(4, 8, 14);
        _rtbLog.ForeColor   = Color.Cyan;
        _rtbLog.ReadOnly    = true;
        _rtbLog.ScrollBars  = RichTextBoxScrollBars.Vertical;
        _rtbLog.BorderStyle = BorderStyle.FixedSingle;

        // Form properties
        Name            = "ServerForm";
        Text            = "Neon Racing 2026 – Server";
        Size            = new Size(640, 640);
        StartPosition   = FormStartPosition.CenterScreen;
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox     = false;
        BackColor       = Color.FromArgb(8, 8, 18);
        ForeColor       = Color.White;
        Paint          += OnFormPaint;
        FormClosing    += (_, _) => StopEverything();

        Controls.AddRange(new Control[]
        {
            _lblTitle,
            _lblSubtitle,
            _lblBindIP,
            _cboIp,
            _lblPort,
            _nudPort,
            _lblMaxPlayers,
            _btnStart,
            _lblConnectedPlayers,
            _lstPlayers,
            _lblServerLog,
            _rtbLog
        });

        _nudPort.EndInit();
        ResumeLayout(false);
        PerformLayout();
    }

    // ── Control field declarations ────────────────────────────────────────────
    private Label      _lblTitle            = null!;
    private Label      _lblSubtitle         = null!;
    private Label      _lblBindIP           = null!;
    private ComboBox   _cboIp               = null!;
    private Label      _lblPort             = null!;
    private NumericUpDown _nudPort          = null!;
    private Label      _lblMaxPlayers       = null!;
    private Button     _btnStart            = null!;
    private Label      _lblConnectedPlayers = null!;
    private ListBox    _lstPlayers          = null!;
    private Label      _lblServerLog        = null!;
    private RichTextBox _rtbLog             = null!;
}
